### ISSUE TITLE
Documentation for different views

### ISSUE THREAD

**Issue by cal-overflow** [cal-overflow/Build-A-Blog#195]
Add documentation for the different views. This can be inside its own markdown file in the repository.

**Make sure to include the metadata `viewProperties`**

**Comment by cal-overflow** [comment]
Use this comment as a reference for some of the view components. I'll include the view properties with the possible values. I'll also include the default value that is used.

### home-view
`viewProperties` is optional for this section, however certain properties are required for a custom headshot image.
```yaml 
viewProperties:
  headshot:
    image: 'headshot.png'  # any file name is allowed (as long as the file can be found). A placeholder will be used if the image is not found
    styling:
      rounding: [ 'none', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', 'full' ] # default value: 'none'
      objectFit: [ 'contain', 'none', 'cover' 'fill', 'scale-down' ] # default value: 'contain'

```

### post-view
`viewProperties` is completely optional for this section
```yaml
viewProperties:
  featureImageStyling: # styles applied to the feature image (applies to only this post!)
    rounding: [ 'none', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', 'full' ] # default value: 'none'
    objectFit: [ 'contain', 'none', 'cover' 'fill', 'scale-down' ] # default value: 'contain'
```

### post-feed
`viewProperties` is completely optional for this section
```yaml
viewProperties:
  imageStyling: # styles applied to the feature images in the post previews (applies to only this section!)
    rounding: [ 'none', 'sm', 'md', 'lg', 'xl', '2xl', '3xl', 'full' ] # default value: 'none'
    objectFit: [ 'contain', 'none', 'cover' 'fill', 'scale-down' ] # default value: 'contain'
```

### contact-view
‼️ `viewProperties` is required for this section
```yaml
viewProperties:
  emailAddress: abc@xyz.com # Any valid email address will work. This is the email address where contact requests will be sent
```
